# Config file
name = "My Project"
version= "1.0.0"
website = "https://example.com"

# Create table
[itmes]
numbers = [1,2,3]
letters = ['a','b','c']

[items.details]
updated = true
author = "John Doe"

[database]
file.type = "sqlite"
file.path = "data.db"

[inline_table]
inline = {name="John Doe", age=30}

[[table_group]]
fruit = "apple"

[[table_group]]
fruit = "orange"

[[table_group]]
fruit = "watermellon "
